/**
 * A replacement typeshed root for the typeshed bypass gate.
 *
 * The question is only whether a *different* root displaces the embedded one, so
 * this ships the smallest stdlib that still lets `import sys` resolve, and no
 * `subprocess` at all. Exclusion is by omission: a module absent from the root
 * cannot resolve, whatever `VERSIONS` says.
 *
 * It cannot be one file. Point the engine at a root without `builtins.pyi` and
 * nothing resolves, `sys` included, so the gate would report a bypass that is
 * really a total failure. These stubs are deliberately thin, not realistic: the
 * shipped `micropython-stdlib-stubs` are the real payload.
 */

/** Enough of `builtins` for pyright to type the probe. Thin on purpose. */
const BUILTINS = `
class object:
    def __init__(self) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class type:
    def __init__(self, o: object) -> None: ...

class function: ...
class ellipsis: ...
class NoneType: ...

class int:
    def __add__(self, other: int) -> int: ...

class float: ...
class complex: ...

class bool(int): ...

class str:
    def __add__(self, other: str) -> str: ...
    def upper(self) -> str: ...

class bytes: ...
class bytearray: ...
class memoryview: ...

class tuple: ...
class list: ...
class dict: ...
class set: ...
class frozenset: ...
class slice: ...
class range: ...

class property: ...
class staticmethod: ...
class classmethod: ...
class super: ...

def print(*values: object) -> None: ...

class BaseException: ...
class Exception(BaseException): ...
class GeneratorExit(BaseException): ...
class StopIteration(Exception): ...
class StopAsyncIteration(Exception): ...
class AttributeError(Exception): ...
class TypeError(Exception): ...
class ValueError(Exception): ...
class KeyError(Exception): ...
class IndexError(Exception): ...
class NameError(Exception): ...
class OSError(Exception): ...
class RuntimeError(Exception): ...
class NotImplementedError(RuntimeError): ...
`;

/** `platform` is the probe. A `str` here is the replacement root answering. */
const SYS = `
platform: str
maxsize: int

def exit(code: int = 0) -> None: ...
`;

/**
 * Present but nearly empty. A module absent from `VERSIONS` is treated as valid,
 * so this filters nothing; it exists because a stdlib root normally has one.
 */
const VERSIONS = `builtins: 3.0-
sys: 3.0-
`;

/** The gate's own module, to prove the root's non-stdlib files resolve too. */
const MICROBIT = `
def panic(n: int) -> None: ...
def sleep(ms: int) -> None: ...
`;

/**
 * Keyed on VFS paths, the shape `initializationOptions.files` takes.
 * `subprocess` is the omission the gate asserts on.
 */
export function replacementTypeshed(root: string): Record<string, string> {
	return {
		[`${root}/stdlib/VERSIONS`]: VERSIONS,
		[`${root}/stdlib/builtins.pyi`]: BUILTINS,
		[`${root}/stdlib/sys/__init__.pyi`]: SYS,
		[`${root}/stdlib/microbit/__init__.pyi`]: MICROBIT,
	};
}

/**
 * The whole acceptance in one file, read by three hovers on `platform`, `panic`
 * and `subprocess`.
 *
 * **Hover the attribute, never a variable assigned from it.** `check = sys.platform`
 * then hovering `check` reports `str` under *both* typesheds, because the embedded
 * stub's `LiteralString` widens on assignment. That reading makes a total failure
 * look like a clean bypass, and it is how the first version of this gate reported
 * a result it had not measured.
 *
 * `microbit` is the decisive one: it exists only in the replacement root, so it
 * cannot resolve by accident.
 *
 * **Probe an attribute for the absent module too.** Hovering `subprocess` itself
 * reports `Module("subprocess")` whether or not the import resolved, so it reads
 * identically in both worlds; the server says `Could not import 'subprocess'` in
 * the same run. `subprocess.Popen` is the honest question: a real class means the
 * embedded typeshed answered.
 */
export const BYPASS_PROBE = [
	'import sys',
	'import subprocess',
	'import microbit',
	'',
	'print(sys.platform)',
	'microbit.panic(1)',
	'print(subprocess.Popen)',
	'',
].join('\n');
