name: Build and Test

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

permissions:
  contents: read

jobs:
  build-test:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Use Node.js 22.x
        uses: actions/setup-node@v7
        with:
          node-version: 22.x
          cache: npm

      - run: npm ci

      - run: npm run typecheck

      - run: npm run build

      - run: npm test

      - name: Integration tests VS Code Web
        run: npm run test:integration

      - name: Integration tests VS Code desktop
        run: xvfb-run -a npm run test:integration:desktop
